function castsToEnum<T extends typeof axisActionEntries[number]>(e: ReadonlyArray<T>) {
	return [...e, ...e.map((x) => x.Name), ...e.map((x) => x.Value)] as ReadonlyArray<
		T | T["Name"] | T["Value"]
	>;
}

export enum GamepadKind {
	None,
	Gamepad1,
	Gamepad2,
	Gamepad3,
	Gamepad4,
	Gamepad5,
	Gamepad6,
	Gamepad7,
	Gamepad8,
}

export const numberAxisEntries = [
	Enum.UserInputType.MouseWheel,
	Enum.KeyCode.ButtonL1,
	Enum.KeyCode.ButtonR1,
	Enum.KeyCode.ButtonL2,
	Enum.KeyCode.ButtonR2,
] as const;

export const vector2AxisEntries = [
	Enum.UserInputType.Accelerometer,
	Enum.UserInputType.MouseMovement,
	Enum.UserInputType.Touch,
	Enum.KeyCode.Thumbstick1,
	Enum.KeyCode.Thumbstick2,
] as const;

export const mouseButtonEntries = [
	Enum.UserInputType.MouseButton1,
	Enum.UserInputType.MouseButton2,
	Enum.UserInputType.MouseButton3,
] as const;

export const numberAxisTypes = castsToEnum(numberAxisEntries);

export const vector2AxisTypes = castsToEnum(vector2AxisEntries);

export const axisActionEntries = [
	Enum.UserInputType.Gyro,
	...numberAxisEntries,
	...vector2AxisEntries,
] as const;

export const unusedKeys = [
	Enum.UserInputType.None,
	Enum.UserInputType.InputMethod,
	Enum.KeyCode.Unknown,
	Enum.KeyCode.World0,
	Enum.KeyCode.World1,
	Enum.KeyCode.World2,
	Enum.KeyCode.World3,
	Enum.KeyCode.World4,
	Enum.KeyCode.World5,
	Enum.KeyCode.World6,
	Enum.KeyCode.World7,
	Enum.KeyCode.World8,
	Enum.KeyCode.World9,
	Enum.KeyCode.World10,
	Enum.KeyCode.World11,
	Enum.KeyCode.World12,
	Enum.KeyCode.World13,
	Enum.KeyCode.World14,
	Enum.KeyCode.World15,
	Enum.KeyCode.World16,
	Enum.KeyCode.World17,
	Enum.KeyCode.World18,
	Enum.KeyCode.World19,
	Enum.KeyCode.World20,
	Enum.KeyCode.World21,
	Enum.KeyCode.World22,
	Enum.KeyCode.World23,
	Enum.KeyCode.World24,
	Enum.KeyCode.World25,
	Enum.KeyCode.World26,
	Enum.KeyCode.World27,
	Enum.KeyCode.World28,
	Enum.KeyCode.World29,
	Enum.KeyCode.World30,
	Enum.KeyCode.World31,
	Enum.KeyCode.World32,
	Enum.KeyCode.World33,
	Enum.KeyCode.World34,
	Enum.KeyCode.World35,
	Enum.KeyCode.World36,
	Enum.KeyCode.World37,
	Enum.KeyCode.World38,
	Enum.KeyCode.World39,
	Enum.KeyCode.World40,
	Enum.KeyCode.World41,
	Enum.KeyCode.World42,
	Enum.KeyCode.World43,
	Enum.KeyCode.World44,
	Enum.KeyCode.World45,
	Enum.KeyCode.World46,
	Enum.KeyCode.World47,
	Enum.KeyCode.World48,
	Enum.KeyCode.World49,
	Enum.KeyCode.World50,
	Enum.KeyCode.World51,
	Enum.KeyCode.World52,
	Enum.KeyCode.World53,
	Enum.KeyCode.World54,
	Enum.KeyCode.World55,
	Enum.KeyCode.World56,
	Enum.KeyCode.World57,
	Enum.KeyCode.World58,
	Enum.KeyCode.World59,
	Enum.KeyCode.World60,
	Enum.KeyCode.World61,
	Enum.KeyCode.World62,
	Enum.KeyCode.World63,
	Enum.KeyCode.World64,
	Enum.KeyCode.World65,
	Enum.KeyCode.World66,
	Enum.KeyCode.World67,
	Enum.KeyCode.World68,
	Enum.KeyCode.World69,
	Enum.KeyCode.World70,
	Enum.KeyCode.World71,
	Enum.KeyCode.World72,
	Enum.KeyCode.World73,
	Enum.KeyCode.World74,
	Enum.KeyCode.World75,
	Enum.KeyCode.World76,
	Enum.KeyCode.World77,
	Enum.KeyCode.World78,
	Enum.KeyCode.World79,
	Enum.KeyCode.World80,
	Enum.KeyCode.World81,
	Enum.KeyCode.World82,
	Enum.KeyCode.World83,
	Enum.KeyCode.World84,
	Enum.KeyCode.World85,
	Enum.KeyCode.World86,
	Enum.KeyCode.World87,
	Enum.KeyCode.World88,
	Enum.KeyCode.World89,
	Enum.KeyCode.World90,
	Enum.KeyCode.World91,
	Enum.KeyCode.World92,
	Enum.KeyCode.World93,
	Enum.KeyCode.World94,
	Enum.KeyCode.World95,
] as const;
